# Tokyo Night — Fuzzel
# ~/.config/fuzzel/fuzzel.ini

dpi-aware=no
icon-theme=Papirus-Dark
width=40
font=JetBrainsMono Nerd Font:size=13
line-height=32
fields=name,generic,comment,categories,filename,keywords
terminal=foot -e
prompt="❯  "
placeholder="Search..."
show-actions=yes
exit-on-keyboard-focus-loss=no
anchor=center

[colors]
background=16161eff
text=c0caf5ff
match=7dcfffff
selection=24283bff
selection-match=7dcfffff
selection-text=c0caf5ff
border=7aa2f7ff
prompt=7aa2f7ff
input=c0caf5ff
counter=565f89ff

[border]
width=2
radius=12
